### ISSUE TITLE
Error in Readme and suggestions

### ISSUE THREAD

**Issue by kristianmandrup** [kasperlewau/koa-h2-man-pusher#4]
`koa.callback()` should be `app.callback()` since `const app = new Koa();`

```js
const spdy = require('spdy');
const Koa = require('koa');
const manpush = require('koa-h2-man-pusher');

const app = new Koa();

app.use(manpush.manifestor({ manifest: 'manifest.json' }));
app.use(manpush.push());

const server = spdy.createServer({ key: 'path/to/ssl.key', cert: 'path/to/ssl.crt' }, app.callback());

server.listen(3000);
```

I suggest making a nice little wrapper for this common setup.

```js
const manpusher = manpush.create(app).configure({ 
  manifest: 'manifest.json', 
  key: 'path/to/ssl.key', 
  cert: 'path/to/ssl.crt' 
})

app
  .use(manpusher.manifestor)
  .use(manpusher.push)

// or using koa-combine
app
  .use(combine(...manpusher.mw)) // returns all middleware in a list

manpusher.server.listen(3000)
```

Cheers!

**Comment by kasperlewau** [comment]
> koa.callback() should be app.callback() since const app = new Koa();

Doh! Thanks. I'll get to it :) 

I'll be rewriting the middleware(s) into one, so no more `.manifestor` or `.push`; 

``` js
const app = new Koa();
app.use(manpush({ manifest: 'manifest.json' }); 
```

---

As far as wrapping `spdy` goes, I think that's something to look at once the major quirks of the push middleware have been taken care of. I do like the idea of having a pre-composed Koa stack w/ push support baked in though 👌

**Comment by kasperlewau** [comment]
@kristianmandrup I'll move this over to a feature request now that the readme issue has been resolved.

**Comment by kristianmandrup** [comment]
Awesome! Sounds good :)
